### ISSUE TITLE
The Hierophant card doesn't give extra xp from killing mob

### ISSUE THREAD

**Issue by AriesStar1337** [shiroroku/TarotCards#13]
**Mod version:** tarotcards-1.20-1.5-release

**Describe the issue:** Killing mob does not give you any extra xp effect from The Hierophant card.

**How to Reproduce:**
1. Have the card in inventory or deck.
2. Kill zombie.
3. Check xp bar.

**Additional info:**
Mining ore and furnace does give extra xp.

**Comment by shiroroku** [comment]
i figured out whats going on, i was casting the multiplied xp values straight into integers, which is basically a floor function, when we want rounding instead

though because minecraft has experience orbs as low integer values, the values wont be perfect at lower numbers
(xp orb with 1 point in it will be x2 despite the card being only 150%)

ill fix this soon
